# Generated by Django 3.2.9 on 2021-12-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
