# Generated by Django 3.2.9 on 2022-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220429_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dis_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
